export const representacaoSet = [
 {
   representacao: "ANA P G DORTA",
   telefone: "66 99223-1283",
   email: null,
   estado_id: "Mato Grosso",
 },
 {
   representacao: "ANA P G DORTA",
   telefone: "66 99223-1283",
   email: null,
   estado_id: "Mato Grosso do Sul",
 },
 {
   representacao: "ANA P G DORTA",
   telefone: "66 99223-1283",
   email: null,
   estado_id: "Acre",
 },
 {
   representacao: "ANA P G DORTA",
   telefone: "66 99223-1283",
   email: null,
   estado_id: "Rondônia",
 },
 {
   representacao: "ANTONIO LUIZ P GUIMARAES REPRESENTAÇÃO",
   telefone: "92 99113-4042",
   email: null,
   estado_id: "Amazonas",
 },
 {
   representacao: "ATHILA MENDES REPRESENTAÇÕES E CONSULTORIA LTDA",
   telefone: "85 8895-0411",
   email: null,
   estado_id: "Ceará",
 },
 {
   representacao: "DAF REPRESENTAÇÕES DE MATERIAIS DE CONSTRUÇÃO LTDA",
   telefone: "91 8843-0698",
   email: null,
   estado_id: "Pará",
 },
 {
   representacao: "DWMG REPRESENTAÇÕES COMERCIAIS LTDA ME",
   telefone: "31 9581-5469",
   email: null,
   estado_id: "Minas Gerais",
 },
 {
   representacao: "EGILDO ALVES REPRESENTAÇÕES LTDA",
   telefone: "63 9977-9718",
   email: null,
   estado_id: "Tocantins",
 },
 {
   representacao: "EGILDO ALVES REPRESENTAÇÕES LTDA",
   telefone: "63 9977-9718",
   email: null,
   estado_id: "Pará",
 },
 {
   representacao: "EGILDO ALVES REPRESENTAÇÕES LTDA",
   telefone: "63 9977-9718",
   email: null,
   estado_id: "Maranhão",
 },
 {
   representacao: "EVOLUÇÃO REPRESENTAÇÕES EIRELI",
   telefone: "79 9986-8699",
   email: null,
   estado_id: "Sergipe",
 },
 {
   representacao: "EVOLUÇÃO REPRESENTAÇÕES EIRELI",
   telefone: "79 9986-8699",
   email: null,
   estado_id: "Bahia",
 },
 {
   representacao: "ATIVVA SOLUÇÕES E INTERMEDIAÇÕES LTDA",
   telefone: "19 98226-4880",
   email: null,
   estado_id: "São Paulo",
 },
 {
   representacao: "F DE A L DE ANDRADE REPRESENTAÇÕES (DRAGONFLY)",
   telefone: "84 9133-1359",
   email: null,
   estado_id: "Rio Grande do Norte",
 },
 {
   representacao: "GIRO REPRESENTAÇÕES DE MATERIAIS DE CONSTRUÇÃO LTDA",
   telefone: "81 9946-3204",
   email: null,
   estado_id: "Pernambuco",
 },
 {
   representacao: "JCAB REPRESENTAÇÕES LTDA ME",
   telefone: "83 9372-9107",
   email: null,
   estado_id: "Paraíba",
 },
 {
   representacao: "JOBSON BORGES DE LIMA",
   telefone: "85 8876-0927",
   email: null,
   estado_id: "Ceará",
 },
 {
   representacao: "JT COMÉRCIO E REPRESENTAÇÕES",
   telefone: "82 8899-5604",
   email: null,
   estado_id: "Alagoas",
 },
 {
   representacao: "KM SILVA REPRESENTAÇÕES LTDA",
   telefone: "93 9122-5807",
   email: null,
   estado_id: "Pará",
 },
 {
   representacao: "KM SILVA REPRESENTAÇÕES LTDA",
   telefone: "93 9122-5807",
   email: null,
   estado_id: "Amazonas",
 },
 {
   representacao: "LEONARDO CESAR BORGES LARANJEIRA",
   telefone: "81 9624-0134",
   email: null,
   estado_id: "Pernambuco",
 },
 {
   representacao: "M E M REPRESENTAÇÕES LTDA",
   telefone: "77 9951-2409",
   email: null,
   estado_id: "Bahia",
 },
 {
   representacao: "MAPA REPRESENTAÇÃO",
   telefone: "98 8881-9642",
   email: null,
   estado_id: "Maranhão",
 },
 {
   representacao: "MAPA REPRESENTAÇÃO",
   telefone: "98 8881-9642",
   email: null,
   estado_id: "Piauí",
 },
 {
   representacao: "MODELO ASSESSORIA DE VENDAS LTDA",
   telefone: "31 8752-1565",
   email: null,
   estado_id: "Minas Gerais",
 },
 {
   representacao: "PRN REPRESENTAÇÕES LTDA",
   telefone: "83 8886-8552",
   email: null,
   estado_id: "Paraíba",
 },
 {
   representacao: "RC REIS JUNIOR COMÉRCIO E REPRESENTAÇÕES",
   telefone: "71 9151-2700",
   email: null,
   estado_id: "Bahia",
 },
 {
   representacao: "RKM SAFFE REPRESENTAÇÕES COMERCIAIS ME",
   telefone: "66 9988-5400",
   email: null,
   estado_id: "Mato Grosso",
 },
 {
   representacao: "RMJ REPRESENTAÇÕES",
   telefone: "62 8415-5750",
   email: null,
   estado_id: "Goiás",
 },
 {
   representacao: "BERITH REPRESENTAÇÕES COMERCIAIS LTDA",
   telefone: "49 9925-1234",
   email: null,
   estado_id: "Santa Catarina",
 },
 {
   representacao: "MALKA REPRESENTAÇÕES LTDA ME",
   telefone: "51 8436-8485",
   email: null,
   estado_id: "Rio Grande do Sul",
 },
 {
   representacao: "RECRIPEL REPRESENTAÇÃO COMERCIAL LTDA",
   telefone: "41 9872-7778",
   email: null,
   estado_id: "Paraná",
 },
 {
   representacao: "REPRESENTAÇÕES COMERCIAIS CORREA",
   telefone: "43 9194-0663",
   email: null,
   estado_id: "Paraná",
 },
 {
   representacao: "RICARDO TRIGO REPRESENTAÇÕES COMERCIAIS LTDA ME",
   telefone: "45 9924-9726",
   email: null,
   estado_id: "Paraná",
 },
 {
   representacao: "SCHMUKER REPRESENTAÇÃO COM LTDA",
   telefone: "41 9679-7778",
   email: null,
   estado_id: "Paraná",
 },
 {
   representacao: "AMPLA VENDAS LTDA",
   telefone: "31 9435-9554",
   email: null,
   estado_id: "Minas Gerais",
 },
 {
   representacao: "ARAUJO E QUEIROZ REPRESENTAÇÕES",
   telefone: "61 9982-2133",
   email: null,
   estado_id: "Distrito Federal",
 },
 {
   representacao: "ARTUR ALBERTO PRATA REPRESENTAÇÕES LTDA",
   telefone: "21 98162-5344",
   email: null,
   estado_id: "Rio de Janeiro",
 },
 {
   representacao: "DCA REPRESENTAÇÕES LTDA",
   telefone: "21 98307-5800",
   email: null,
   estado_id: "Rio de Janeiro",
 },
 {
   representacao: "FAMPAR REPRESENTAÇÕES LTDA",
   telefone: "61 8435-2123",
   email: null,
   estado_id: "Distrito Federal",
 },
 {
   representacao: "FAZZI REPRESENTAÇÕES COMERCIAIS DE MATERIAIS DE CONSTRUÇÃO LTDA",
   telefone: "31 8476-7257",
   email: null,
   estado_id: "Minas Gerais",
 },
 {
   representacao: "FRESMAX DO BRASIL LTDA",
   telefone: "32 9985-0907",
   email: null,
   estado_id: "Minas Gerais",
 },
 {
   representacao: "G2S REPRESENTAÇÕES LTDA",
   telefone: "27 98134-6077",
   email: null,
   estado_id: "Espírito Santo",
 },
 {
   representacao: "GVA GESTÃO DE NEGÓCIOS LTDA",
   telefone: "21 99907-5597",
   email: null,
   estado_id: "Rio de Janeiro",
 },
 {
   representacao: "M J E MABERT REPRESENTAÇÕES COMERCIAIS LTDA",
   telefone: "21 99907-5597",
   email: null,
   estado_id: "Rio de Janeiro",
 },
 {
   representacao: "MN MARCELO REPRES. DE EQUIP. DE METAL LTDA",
   telefone: "21 96902-4836",
   email: null,
   estado_id: "Rio de Janeiro",
 },
 {
   representacao: "NETO OLIVEIRA REPRESENTAÇÕES LTDA ME",
   telefone: "34 9194-7840",
   email: null,
   estado_id: "Minas Gerais",
 },
 {
   representacao: "SARAIVA REPRESENTAÇÕES LTDA",
   telefone: "38 99922-9898",
   email: null,
   estado_id: "Minas Gerais",
 },
 {
   representacao: "SD PROMOÇÕES E VENDAS",
   telefone: "31 9197-4343",
   email: null,
   estado_id: "Minas Gerais",
 },
 {
   representacao: "TC REPRESENTAÇÕES",
   telefone: "19 99171-3918",
   email: null,
   estado_id: "São Paulo",
 },
 {
   representacao: "ATIVVA SOLUÇÕES E INTERMEDIAÇÕES LTDA",
   telefone: "19 98226-4880",
   email: null,
   estado_id: "São Paulo",
 },
 {
   representacao: "ELTON REPRESENTAÇÕES COMERCIAIS LTDA",
   telefone: "14 99840-8565",
   email: null,
   estado_id: "São Paulo",
 },
 {
   representacao: "EMGRS REPRESENTAÇÃO LTDA",
   telefone: "11 96890-0677",
   email: null,
   estado_id: "São Paulo",
 },
 {
   representacao: "FERRAMENTAS RIBEIRÃO PRETO LTDA ME (DONY REPRESENTAÇÕES)",
   telefone: "16 99165-2360",
   email: null,
   estado_id: "São Paulo",
 },
 {
   representacao: "HR LORENCETTI REPRESENTAÇÕES",
   telefone: "19 99708-3957",
   email: null,
   estado_id: "São Paulo",
 },
 {
   representacao: "LN VENDRAMI REPRESENTAÇÕES",
   telefone: "19 99951-1943",
   email: null,
   estado_id: "São Paulo",
 },
 {
   representacao: "LT REPRESENTAÇÕES COMERCIAIS",
   telefone: "11 99991-1088",
   email: null,
   estado_id: "São Paulo",
 },
 {
   representacao: "M23 REPRESENTAÇÃO COMERCIAL LTDA",
   telefone: "11 94137-1118",
   email: null,
   estado_id: "São Paulo",
 },
 {
   representacao: "MASSAROTO REPRESENTAÇÕES COMERCIAIS",
   telefone: "19 99746-3530",
   email: null,
   estado_id: "São Paulo",
 },
 {
   representacao: "RS BURACIA",
   telefone: "11 94017-4968",
   email: null,
   estado_id: "São Paulo",
 },
 {
   representacao: "TC REPRESENTAÇÕES",
   telefone: "19 99171-3918",
   email: null,
   estado_id: "São Paulo",
 },
 {
   representacao: "V R M RIO PRETO REPRESENTAÇÕES COMERCIAIS LTDA",
   telefone: "17 98171-2413",
   email: null,
   estado_id: "São Paulo",
 }
];